baseURL = 'http://deepakwrites.com/'
languageCode = 'en-us'
title = 'Deepak Writes'
theme = "anatole"
DefaultContentLanguage = "en"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"


[params]
displayMode = "light"
title = "Deepak Kumar"
author = "Deepak Kumar"
profilePicture = "images/2023_hs_option_1.jpg"
doNotLoadAnimations = true
contentratio = 0.6

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/_kumarde"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://www.twitter.com/_kumarde"

[[params.socialIcons]]
icon = "fab fa-soundcloud"
title = "Soundcloud"
url = "https://soundcloud.com/kumarde"
