baseURL = 'http://deepakwrites.com/'
languageCode = 'en-us'
title = 'Deepak Writes'
theme = "anatole"
DefaultContentLanguage = "en"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"


[params]
title = "Deepak Kumar"
author = "Deepak Kumar"
profilePicture = "images/headshot.png"
doNotLoadAnimations = true
contentratio = 0.6
displayMode = "light"
